In [8]:
import pandas as pd

In [9]:
#checking for encoding/delimiter error and specifying dtype for string/bool columns

df = pd.read_csv('Messy_Employee_dataset.csv',
                 encoding = 'utf-8',
                 sep = ',',
                dtype = {'Employee_ID':'string',
                         'First_Name':'string',
                         'Last_Name':'string',
                         'Department_Region':'string',
                         'Status':'string',
                         'Email':'string',
                         'Performance_Score':'string',
                         'Remote_Work':'bool'
                         }
                )
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [10]:
#fixing column types for numerical columns + date column

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.0,HR-California,Active,2023-08-19,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [11]:
#checking for missing

df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [12]:
#standardising whitespace and capitalisation
df.columns = df.columns.str.lower().str.replace(' ', '_').str.strip()
df

#setting employee_id as index
df.set_index('employee_id', inplace=True)

In [22]:
#fixing phone column
df['phone'] = df['phone'].astype(str)
df

,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work
employee_id,,,,,,,,,,,
EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True
EMP1001,Bob,Brown,30.0,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True
EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True
EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True
EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...
EMP2014,Grace,Jones,30.0,Finance-Nevada,Pending,2021-05-16,51990.98,grace.jones@example.com,2470739200,Excellent,True
EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,2508261122,Good,True
EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,1261632487,Average,False
EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,8995729892,Good,True
EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,7629745492,Average,False

In [23]:
#handle missing data

df.isnull().sum()

df.dropna(subset = ['salary'], inplace=True) #cannot really impute any value for salary as it is specific to job role and other quantifiers - best to be removed

df['age'] = df['age'].fillna(df['age'].median())

In [24]:
#check again for missing values
df.isnull().sum()

first_name           0
last_name            0
age                  0
department_region    0
status               0
join_date            0
salary               0
email                0
phone                0
performance_score    0
remote_work          0
dtype: int64

In [25]:
#remove '-' sign for phone numbers
df['phone'] = df['phone'].str.replace(r'\D','', regex=True)

df

,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work
employee_id,,,,,,,,,,,
EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True
EMP1001,Bob,Brown,30.0,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True
EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True
EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True
EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...
EMP2014,Grace,Jones,30.0,Finance-Nevada,Pending,2021-05-16,51990.98,grace.jones@example.com,2470739200,Excellent,True
EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,2021-11-07,100215.06,david.johnson@example.com,2508261122,Good,True
EMP2017,Charlie,Williams,40.0,Finance-New York,Active,2023-10-04,114587.11,charlie.williams@example.com,1261632487,Average,False
EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,2024-12-16,71318.79,alice.garcia@example.com,8995729892,Good,True
EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2021-02-22,77764.24,heidi.jones@example.com,7629745492,Average,False

In [27]:
#export to .csv
df.to_csv('cleaned_employee_dataset.csv', index = True)